[package]
name = "game_remover-rust"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"

[dependencies]
eframe = "0.33.0"
egui-async = "0.2.3"
egui_extras = "0.33.0"
env_logger = "0.11.8"
reqwest = "0.12.24"
serde = { version = "1.0.228", features = ["derive"] }
