[package]
name = "game-remover-rust"
version = "0.1.0"
authors = ["pastaya <contact@pastaya.net>"]
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
tokio = { version = "1.48.0", features = ["full"] }
